### ISSUE TITLE
Correlation Id Support

### ISSUE THREAD

**Issue by gianlucafrei** [gianlucafrei/Application-Gateway#34]
- Read correlation id from header or create a new one
- Forward correlation id upstream
- Use correlation for logs

**Comment by quadaloop** [comment]
Kannst du mir noch die Rechte zum bearbeiten von Tickets geben (assign, edit Description etc)

**Comment by Padi-owasp** [comment]
This will be based on W3C Trace Context specification (Main implementation) and allow also a custom implementation/headers to be used.

**Comment by Padi-owasp** [comment]
Link to W3c spec: https://w3c.github.io/trace-context/
Branch: 34-correlation-id

**Comment by gianlucafrei** [comment]
Configuration file:
```yaml

features:
    tracing:
       type: w3c #(Spring bean name) w3c, none or other
       with:
            implementation-specific-setting: foo
            ...
```
